* Tiled image processing
  :PROPERTIES:
  :CUSTOM_ID: tiled-image-processing
  :END:
If image data is too large to fit into memory, it becomes necessary to
split the image into multiple /tiles/ and process them individually.
While this step is straightforward, it can become very challenging to
stitch the resulting image tiles together and return one big result
image. In this section we will elaborate on multiple strategies to deal
with tiled image processing. The
[[https://docs.dask.org/en/stable/][dask library]] enables processing
tiled images easy to use. This chapter starts with a complete workflow
showing dask in action and then explains the individual steps for
setting up a proper workflow for processing your data afterwards.

See also * Genevieve Buckley's talk about
[[https://www.youtube.com/watch?v=MpjgzNeISeI&t=1359s]["dask-image:
distributed image processing for large data"]] (PyConline AU 2020)
[[https://genevievebuckley.github.io/dask-image-talk-2020/][Slides]] *
John Kirkham's talk about
[[https://www.youtube.com/watch?v=XGUS174vvLs]["dask image:A Library for
Distributed Image Processing"]] (SciPy 2019) *
[[https://docs.dask.org/en/stable/][Dask documentation]] *
[[http://image.dask.org/en/latest/][Dask image documentation]] *
[[https://examples.dask.org/applications/image-processing.html][Dask
examples: image processing]] * https://github.com/VolkerH/DaskFusion
