* GPU accelerated image processing
  :PROPERTIES:
  :CUSTOM_ID: gpu-accelerated-image-processing
  :END:
As we work often with three-dimensional image data, potentially over
time, classical image processing takes quite some time.

Hence, we will also dive into image processing on graphics processing
units (GPUs) using [[https://www.khronos.org/opencl/][OpenCL]],
[[https://documen.tician.de/pyopencl/][pyopencl]] and
[[https://github.com/clesperanto/pyclesperanto_prototype][pyclesperanto]].
This technology allows us to process image faster, GPU accelerated.
Classical algorithms and GPU-accelerated image processing may differ in
the very details but we users should not recognize that. A specific
image processing operation should deliver similar results independent
from how it is computed.

** Installation of requirements
   :PROPERTIES:
   :CUSTOM_ID: installation-of-requirements
   :END:
User of Windows and Mac should not need to install OpenCL. Everything
you need should be pre-installed. Linux users need to install an
OpenCL-ICD-Loader.

Hence, linux users may have to run commands like this, depending on the
linux distribution:

#+begin_example
sudo apt update
sudo apt install ocl-icd-opencl-dev
#+end_example

Afterwards, installation can proceed using conda /and/ pip:

#+begin_example
mamba install -c conda-forge l pyclesperanto-prototype
#+end_example

Afterwards, you can test it for example by executing these commands in a
python script or jupyter notebook:

#+begin_example
import pyclesperanto_prototype as cle

print("Used GPU:", cle.get_device())
#+end_example

Also feel free to install the
[[https://clesperanto.github.io/napari_pyclesperanto_assistant/][napari-pyclesperanto-assistant
plugin in napari]].

** Installation of optional requirements
   :PROPERTIES:
   :CUSTOM_ID: installation-of-optional-requirements
   :END:
In this chapter, we will also take a look at [[https://cupy.dev][cupy]],
an [[https://en.wikipedia.org/wiki/CUDA][NVidia CUDA]] based
GPU-accelerated processing library and
[[https://github.com/haesleinhuepf/napari-cupy-image-processing][napari-cupy-image-processing]],
a scriptable napari plugin. These two can be installed using the
following commands. This will however only work on computers that have a
CUDA-compatible NVidia graphics card.

#+begin_example
mamba install -c conda-forge cupy cudatoolkit=10.2
mamba install -c conda-forge napari
pip install napari-cupy-image-processing
#+end_example

Note: Depending on your CUDA installation, you may want to replace the
"10.2" in the command line above with the CUDA version you installed on
your computer.

See also * [[https://www.youtube.com/watch?v=z9fk9d6pry4][Performance of
dedicated laptop GPUs versus desktop GPUs (Linus Tech Tips video)]] *
[[https://docs.cupy.dev/en/stable/install.html#installing-cupy][Cupy
installation]]
