* Advanced python programming
  :PROPERTIES:
  :CUSTOM_ID: advanced-python-programming
  :END:
In this chapter we will take a closer look at what's possible with
Python. We will dive into types, workflows, decorators and functions
that take functions as parameters that take functions as parameters that
take functions as parameter. If you're more interested in image
analysis, you can skip this chapter for now and come back later when you
see a reference pointing here. It's not mandatory to understand all the
concepts here for understanding the following sections.

** Python libraries used in this chapter
   :PROPERTIES:
   :CUSTOM_ID: python-libraries-used-in-this-chapter
   :END:
Therefore, we'll be introducing other Python libraries for dealing with
data and workflows, called [[https://dask.dev][dask]], and
[[https://joblib.readthedocs.io/en/latest/index.html][joblib]] for
parallelization. We will also take a look at the
[[https://github.com/haesleinhuepf/napari-workflows][napari-workflows]]
library which brings some convenience to knit dask and napari together.
You can install them as simple as this:

#+begin_example
pip install "dask[array]"
pip install "dask[distributed]"
pip install joblib
pip install napari-workflows
#+end_example

In one example we will also use [[https://numba.pydata.org/][numba]] for
compiling python code to speedup execution.

#+begin_example
conda install numba
#+end_example
