* Image deconvolution
  :PROPERTIES:
  :CUSTOM_ID: image-deconvolution
  :END:
Image deconvolution is also /just/ a special form of image filtering. We
dedicate a whole chapter to it because deconvolutions play an important
role in fluorescence microscopy.

We will demonstrate the principles in two dimensional images. It shall
be highlighted though that deconvolution should be done in three
dimensions if possible because the physical principles behind are not
the same in all directions, the point spread function is typically not
symmetrical in fluorescence microscopy.

** Installing requirements
   :PROPERTIES:
   :CUSTOM_ID: installing-requirements
   :END:
We will use
[[https://github.com/rosalindfranklininstitute/RedLionfish][RedLionFish]]
and [[https://simpleitk.readthedocs.io/][SimpleITK]] for deconvolving
images. For the ease-of-use, we will work with the latter via a
convenience layer,
[[https://github.com/haesleinhuepf/napari-simpleitk-image-processing][napari-simpleitk-image-processing]].
Enter these commands in the terminal to install everything:

#+begin_example
mamba install reikna pyopencl -c conda-forge
pip install redlionfish
pip install napari-simpleitk-image-processing
#+end_example

#+begin_html
  <!--
  ## Installing optional dependencies

  In one notebook we will also use NVidia CUDA for deconvolution. If your graphics processing unit supports cuda, feel free to install [pycudadecon](https://github.com/tlambert03/pycudadecon).

  ```
  mamba install -c conda-forge pycudadecon
  ```
  -->
#+end_html

** See also
   :PROPERTIES:
   :CUSTOM_ID: see-also
   :END:
- [[https://www.biodip.de/wiki/How_to_deconvolve_images_using_Huygens][BioDIP
  Dresden, How to deconvolve images using Huygens]]
